language: python 
python: 
  - "3.6"
services: 
  - postgresql
env: 
  - DJANGO=2.1.2 DB=postgresql
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script: 
  - pytest
after_success: coveralls
