language: python 
    python: 
      - "2.6"
      - "2.7"
      - "3.7"
    services: 
      - postgresql
    env: 
      -DJANGO=2.1 DB=postgresql
    install: 
      - pip install -r requirements.txt
    before_script: 
      - psql -c 'create database testdb;' -U postgres
      - python3 manage.py migrate
    script: 
      - pytest --cov=authors
    after_script:
      - coveralls