language: python 
python: 
  - "3.6"
services: 
  - postgresql
env: 
  - DJANGO=2.1 DB=postgresql
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script: 
  - nosetests --with-coverage --cover-package=authors && coverage report
after_script:
  - coveralls
